name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker (if needed)
        run: echo "Docker already installed on self-hosted runner"

      - name: Pull latest changes
        run: git pull origin main

      - name: Rebuild and deploy
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d --build
